version: 2.1

jobs:
  Run_Ubuntu:
    docker:
      - image: node:latest
    steps:
      # Checkout the code from your Git repository
      - checkout
      
      # Install npm dependencies
      - run:
          name: Install npm dependencies
          command: pwd && ls && npm install

      # Install expect (required for automated input)
      - run:
          name: Install expect
          command: apt-get update && apt-get install -y expect

      # Run the script with automated input using expect
      - run:
          name: Test Combination m y y
          command: |
            /usr/bin/expect \<<EOD
            spawn npm run linux
            expect "Which database you want to install?"
            send "m\r"
            expect "Do you want to install jsonwebtoken for authentication?"
            send "y\r"
            expect "Do you want to include request validation?"
            send "y\r"
            expect eof
            EOD

      - run:
          name: Test Combination m y n
          command: |
            /usr/bin/expect \<<EOD
            spawn npm run linux
            expect "Which database you want to install?"
            send "m\r"
            expect "Do you want to install jsonwebtoken for authentication?"
            send "y\r"
            expect "Do you want to include request validation?"
            send "n\r"
            expect eof
            EOD

      - run:
          name: Test Combination m n n
          command: |
            /usr/bin/expect \<<EOD
            spawn npm run linux
            expect "Which database you want to install?"
            send "m\r"
            expect "Do you want to install jsonwebtoken for authentication?"
            send "n\r"
            expect "Do you want to include request validation?"
            send "n\r"
            expect eof
            EOD

      - run:
          name: Test Combination m n y
          command: |
            /usr/bin/expect \<<EOD
            spawn npm run linux
            expect "Which database you want to install?"
            send "m\r"
            expect "Do you want to install jsonwebtoken for authentication?"
            send "n\r"
            expect "Do you want to include request validation?"
            send "y\r"
            expect eof
            EOD      
      # Start the project
      - run:
          name: Start the project
          command: ls

workflows:
  version: 2
  build:
    jobs:
      - Run_Ubuntu