version: 2.1

jobs:
  Run_Ubuntu:
    docker:
      - image: node:latest
    steps:
      # Checkout the code from your Git repository
      - checkout
      
      # Install npm dependencies
      - run:
          name: Install npm dependencies
          command: pwd && ls && npm install          

      # Run for different combinations of inputs
      - run:
          name: Remove dir
          command: rm -rf ExpressJs
      - run:
          name: Test Combination m y y 1
          command:  echo -e "m\n" | npm run linux

      - run:
          name: Test Combination m y y 2
          command: echo -e "y\n"
            

      - run:
          name: Test Combination m y y 3
          command: echo -e "y\n"

      - run:
          name: show dir
          command: ls

      # - run:
      #     name: Start the project
      #     command: ls

workflows:
  version: 2
  build:
    jobs:
      - Run_Ubuntu
