version: 2.1

jobs:
  Run_Ubuntu:
    docker:
      - image: node:latest
    steps:
      # Checkout the code from your Git repository
      - checkout
      
      # Install npm dependencies
      - run:
          name: Install npm dependencies
          command: pwd && ls && npm install          

      # Run for different combinations of inputs
      - run:
          name: Test Combination m y y
          command: rm -rf ExpressJs && echo -e "m\ny\ny\n" | npm run linux

      - run:
          name: Test Combination m y n
          command: rm -rf ExpressJs && echo -e "m\ny\nn\n" | npm run linux
            

      - run:
          name: Test Combination m n y
          command: rm -rf ExpressJs && echo -e "m\nn\ny\n" | npm run linux

      - run:
          name: Test Combination m n n
          command: rm -rf ExpressJs && echo -e "m\nn\nn\n" | npm run linux

      - run:
          name: Start the project
          command: ls

workflows:
  version: 2
  build:
    jobs:
      - Run_Ubuntu
