version: 2.1

jobs:
  Run_Ubuntu:
    docker:
      - image: node:latest
    steps:
      # Checkout the code from your Git repository
      - checkout

      # Install npm dependencies
      - run:
          name: Install npm dependencies
          command: pwd && ls && npm install

      # Install expect (required for automated input)
      - run:
          name: Install expect
          command: apt-get update && apt-get install -y expect

      # Run the script with automated input using expect
      - run:
          name: Test Combination m y y
          command: |
            /usr/bin/expect \<<EOD
            spawn npm run linux
            expect "Which database you want to install?"
            send "m\r"
            expect "Do you want to install jsonwebtoken for authentication?"
            send "y\r"
            expect "Do you want to include request validation?"
            send "y\r"
            expect eof
            EOD

      - run:
          name: Remove ExpressJs dir
          command: rm -rf ExpressJs

      - run:
          name: Test Combination m y n
          command: |
            /usr/bin/expect \<<EOD
            spawn npm run linux
            expect "Which database you want to install?"
            send "m\r"
            expect "Do you want to install jsonwebtoken for authentication?"
            send "y\r"
            expect "Do you want to include request validation?"
            send "n\r"
            expect eof
            EOD

      - run:
          name: Remove ExpressJs dir
          command: rm -rf ExpressJs

      - run:
          name: Test Combination m n n
          command: |
            /usr/bin/expect \<<EOD
            spawn npm run linux
            expect "Which database you want to install?"
            send "m\r"
            expect "Do you want to install jsonwebtoken for authentication?"
            send "n\r"
            expect "Do you want to include request validation?"
            send "n\r"
            expect eof
            EOD

      - run:
          name: Remove ExpressJs dir
          command: rm -rf ExpressJs

      - run:
          name: Test Combination m n y
          command: |
            /usr/bin/expect \<<EOD
            spawn npm run linux
            expect "Which database you want to install?"
            send "m\r"
            expect "Do you want to install jsonwebtoken for authentication?"
            send "n\r"
            expect "Do you want to include request validation?"
            send "y\r"
            expect eof
            EOD

      - run:
          name: Remove ExpressJs dir
          command: rm -rf ExpressJs

      - run:
          name: Test Combination s y y
          command: |
            /usr/bin/expect \<<EOD
            spawn npm run linux
            expect "Which database you want to install?"
            send "s\r"
            expect "Do you want to install jsonwebtoken for authentication?"
            send "y\r"
            expect "Do you want to include request validation?"
            send "y\r"
            expect eof
            EOD

      - run:
          name: Remove ExpressJs dir
          command: rm -rf ExpressJs

      - run:
          name: Test Combination s y n
          command: |
            /usr/bin/expect \<<EOD
            spawn npm run linux
            expect "Which database you want to install?"
            send "s\r"
            expect "Do you want to install jsonwebtoken for authentication?"
            send "y\r"
            expect "Do you want to include request validation?"
            send "n\r"
            expect eof
            EOD

      - run:
          name: Remove ExpressJs dir
          command: rm -rf ExpressJs

      - run:
          name: Test Combination s n n
          command: |
            /usr/bin/expect \<<EOD
            spawn npm run linux
            expect "Which database you want to install?"
            send "s\r"
            expect "Do you want to install jsonwebtoken for authentication?"
            send "n\r"
            expect "Do you want to include request validation?"
            send "n\r"
            expect eof
            EOD

      - run:
          name: Remove ExpressJs dir
          command: rm -rf ExpressJs

      - run:
          name: Test Combination s n y
          command: |
            /usr/bin/expect \<<EOD
            spawn npm run linux
            expect "Which database you want to install?"
            send "s\r"
            expect "Do you want to install jsonwebtoken for authentication?"
            send "n\r"
            expect "Do you want to include request validation?"
            send "y\r"
            expect eof
            EOD

      # Start the project
      - run:
          name: Check for ExpressJs dir
          command: ls

  Run_windows:
    docker:
      - image: dockurr/windows

    steps:
      - checkout

      - run:
          name: Check if PowerShell is installed
          command: |
            powershell -Command "Write-Host 'PowerShell is available!'"

      - run:
          name: Install PowerShell
          command: |
            choco install powershell-core
            powershell -Command "Write-Host 'PowerShell is installed!'"



      - run:
          name: Install Cygwin and Expect
          command: |
            Invoke-WebRequest -Uri 'https://www.cygwin.com/setup-x86_64.exe' -OutFile 'setup-x86_64.exe'
            Start-Process 'setup-x86_64.exe' -ArgumentList '/quiet', '/install', '/packages', 'expect' -NoNewWindow -Wait
            cygwin --version
            expect --version

      - run:
          name: Install rimraf
          command: npm install rimraf

      - run:
          name: Install Node
          command: |
            choco install nodejs-lts

      - run:
          name: Check node version
          command: |
            node -v

      - run:
          name: Install npm dependencies
          command: npm install

      - run:
          name: Test Combination m y y
          command: |
            /usr/bin/expect \<<EOD
            spawn npm run linux
            expect "Which database you want to install?"
            send "m\r"
            expect "Do you want to install jsonwebtoken for authentication?"
            send "y\r"
            expect "Do you want to include request validation?"
            send "y\r"
            expect eof
            EOD

      - run:
          name: Remove ExpressJs dir
          command: rimraf ExpressJs

      - run:
          name: Test Combination m y n
          command: |
            /usr/bin/expect \<<EOD
            spawn npm run linux
            expect "Which database you want to install?"
            send "m\r"
            expect "Do you want to install jsonwebtoken for authentication?"
            send "y\r"
            expect "Do you want to include request validation?"
            send "n\r"
            expect eof
            EOD

      - run:
          name: Remove ExpressJs dir
          command: rimraf ExpressJs

      - run:
          name: Test Combination m n y
          command: |
            /usr/bin/expect \<<EOD
            spawn npm run linux
            expect "Which database you want to install?"
            send "m\r"
            expect "Do you want to install jsonwebtoken for authentication?"
            send "n\r"
            expect "Do you want to include request validation?"
            send "y\r"
            expect eof
            EOD

      - run:
          name: Remove ExpressJs dir
          command: rimraf ExpressJs

      - run:
          name: Test Combination m n n
          command: |
            /usr/bin/expect \<<EOD
            spawn npm run linux
            expect "Which database you want to install?"
            send "m\r"
            expect "Do you want to install jsonwebtoken for authentication?"
            send "n\r"
            expect "Do you want to include request validation?"
            send "n\r"
            expect eof
            EOD

      - run:
          name: Check for ExpressJs dir
          command: powershell -Command "Get-ChildItem -Path ."

workflows:
  version: 2
  build:
    jobs:
      - Run_Ubuntu
      - Run_windows
