version: 2.1

jobs:
  Pull_and_Publish:
    docker:
      - image: node:latest
    steps:
      - checkout

      - run:
          name: Install npm dependencies
          command: npm install

      - run:
          name: Produce build
          command: npm run build

      - run:
          name: Set_Auth_Token
          command: echo "//registry.npmjs.org/:_authToken=${NPM_AUTH_TOKEN}" > ~/.npmrc

      - run:
          name: Publish to npm registry
          command: npm publish --registry https://registry.npmjs.org --access public

workflows:
  version: 2
  build:
    jobs:
      - Pull_and_Publish:
          name: Publish to NPM Registry
          filters:
            branches:
              only: main
